apiVersion: sre.sre.dev/v1alpha1
kind: SLOPolicy
metadata:
  name: sample-slopolicy
spec:
  targetDeployment: nginx-demo
  targetURL: http://nginx-demo.default.svc.cluster.local
  sloTargetPercent: 99.9
  checkIntervalSeconds: 15
  remediationAction: RestartDeployment
